[build]
  command = "npm run build"
  publish = "dist"

# Pliki statyczne (JS, CSS, obrazy) mają unikalne nazwy (hashe), więc możemy je cache'ować "na zawsze"
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Plik wejściowy index.html musi być zawsze świeży, aby wskazywać na nowe pliki JS/CSS
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"